# Some useful aliases
# The .bashrc file source this file

alias file='file -z'
alias mkdir='mkdir -p'

# tmux aliases
alias tns='tmux new-session -s'
alias ta='tmux attach'
alias tat='tmux attach -t'
alias tls='tmux ls'

# vim aliases
alias e='nvim.appimage'
alias vi='nvim.appimage'
alias vim='nvim.appimage'
alias nvim='nvim.appimage'

# emacs aliases
alias emacs='emacs &'
#alias emacs='emacs --no-window-system'

# Internet
alias brave='brave > /dev/null &'
alias firefox='firefox > /dev/null &'
